import type { Study } from "@/lib/types";

export function studySchemaInstructions() {
  return `Return only valid JSON matching this TypeScript shape:
{
  "passage": string,
  "translation": string,
  "mode": string,
  "book": string,
  "sourceProfile": string,
  "generatedAt": string,
  "generationStatus": "generated",
  "bookLinks": string[],
  "people": string[],
  "places": string[],
  "groups": string[],
  "storyContext": string[],
  "eventThreads": string[],
  "entityLinks": string[],
  "themes": string[],
  "tags": string[],
  "sources": string[],
  "bigIdea": string,
  "context": string[],
  "passageMap": [string, string, string][],
  "verseNotes": Array<{
    "reference": string,
    "note": string,
    "details": string[],
    "guardrails"?: string[],
    "application"?: string[],
    "crossReferences"?: [string, string][],
    "keep": string
  }>,
  "crossReferences": [string, string][],
  "translationNotes": Array<{ "reference": string, "note": string, "translations": string[] }>,
  "claimLedger": Array<{ "claim": string, "evidence": string, "sourceType": "scripture" | "commentary" | "dictionary" | "language" | "background" | "vault" | "application", "confidence": "clear" | "strong" | "supported" | "possible" | "application" }>,
  "questions": string[],
  "application": string[],
  "sourceRecords": Array<{ "id": string, "label": string, "type": "scripture" | "commentary" | "dictionary" | "language" | "background" | "vault" | "application", "reference"?: string, "url"?: string, "note"?: string }>,
  "sourceNotes": string[]
}`;
}

export function buildStudyPrompt(input: { passage: string; translation: string; mode: string }) {
  return `Create a Scripture Threads Bible study note.

Passage: ${input.passage}
Preferred translation: ${input.translation}
Mode: ${input.mode}
Doctrinal posture: Scripture-first evangelical, non-denominational, continuationist-friendly.

Requirements:
- Do not invent commentary citations or claim direct source support you do not have.
- Keep chunks usable, not bloated.
- Integrate application, cross references, context, and guardrails inside the verse-by-verse notes.
- Include short cross-reference connection statements.
- Use Obsidian wikilinks for book/person/place/entity arrays, such as [[2 Chronicles]].
- If exact Bible translation text is not supplied, summarize rather than quoting full copyrighted passages.
- Be explicit when a point is application rather than direct textual claim.
- Return JSON only so the result can be imported back into Scripture Threads.

${studySchemaInstructions()}`;
}

export function extractJson(text: string) {
  const trimmed = text.trim();
  const fenced = trimmed.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/);
  if (fenced) return fenced[1];
  const start = trimmed.indexOf("{");
  const end = trimmed.lastIndexOf("}");
  if (start >= 0 && end > start) return trimmed.slice(start, end + 1);
  return trimmed;
}

export function normalizeGeneratedStudy(value: unknown, input: { passage: string; translation: string; mode: string }): Study {
  const data = value && typeof value === "object" ? (value as Partial<Study>) : {};
  return {
    passage: data.passage || input.passage,
    translation: data.translation || input.translation,
    mode: data.mode || input.mode,
    book: data.book || input.passage.replace(/\s+\d.*$/, ""),
    sourceProfile: data.sourceProfile || "Scripture-first evangelical, non-denominational, continuationist-friendly",
    generatedAt: new Date().toISOString(),
    generationStatus: "generated",
    bookLinks: data.bookLinks || [],
    people: data.people || [],
    places: data.places || [],
    groups: data.groups || [],
    storyContext: data.storyContext || [],
    eventThreads: data.eventThreads || [],
    entityLinks: data.entityLinks || [],
    themes: data.themes || [],
    tags: data.tags || [],
    sources: data.sources || ["AI-generated draft"],
    bigIdea: data.bigIdea || "Generated study draft.",
    context: data.context || [],
    passageMap: data.passageMap || [],
    verseNotes: data.verseNotes || [],
    crossReferences: data.crossReferences || [],
    translationNotes: data.translationNotes || [],
    claimLedger: data.claimLedger || [],
    questions: data.questions || [],
    application: data.application || [],
    sourceRecords: data.sourceRecords || [],
    sourceNotes: data.sourceNotes || ["Generated by connected AI provider. Review claims before teaching or exporting."]
  };
}

export function parseStudyJson(text: string, input: { passage: string; translation: string; mode: string }) {
  return normalizeGeneratedStudy(JSON.parse(extractJson(text)), input);
}
